---
- name: Init
  hosts: node
  gather_facts: false
  roles:
    - init
  tags:
    - init

- name: Install and Configure zsh
  hosts: node
  vars_files: roles/zsh/vars/gantsign.oh-my-zsh.yml
  roles:
    - gantsign.oh-my-zsh
    - zsh
  tags:
    - zsh

- name: Install and Configure python
  hosts: node
  roles:
    - role: python
  tags:
    - python

- name: Install and Configure node
  hosts: node
  vars_files: roles/node/vars/stephdewit.nvm.yml
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
  roles:
    - role: stephdewit.nvm
      become: true
      become_user: "{{ ansible_env.USER }}"
    - role: node
  tags:
    - node

- name: Install and Configure golang
  hosts: node
  roles:
    - role: golang
  tags:
    - golang

- name: Install and Configure docker
  hosts: node
  vars_files: vars/global.yml
  roles:
    - role: docker
  tags:
    - docker
