---
- name: Init
  hosts: worker
  gather_facts: false
  roles:
    - init
  tags:
    - init

- name: Oh my zsh
  hosts: node
  roles:
    - gantsign.oh-my-zsh
  vars_files: vars/gantsign.oh-my-zsh.yml
