---
- name: Init
  hosts: node
  gather_facts: false
  roles:
    - init
  tags:
    - init

- name: Install and Setting zsh
  hosts: node
  vars_files: roles/zsh/vars/gantsign.oh-my-zsh.yml
  roles:
    - gantsign.oh-my-zsh
    - zsh
  tags:
    - zsh