---
# Description alias for zsh
zsh_alias:
  # Git
  gac: git add . && git commit
  gst: git status
  gstb: git status -sb
  glog: git log --oneline --decorate --graph
  # Docker
  dc: docker compose
  dps: docker ps -as
  dlog: docker logs --tail 50 --follow --timestamps
  # Minikube
  mk: minikube
  mkst: minikube status
  mkc: minikube kubectl --
  mkca: minikube kubectl -- apply -f
  mkcrm: minikube kubectl -- delete
  mkcrmf: minikube kubectl -- delete -f
  mkcg: minikube kubectl -- get
  mkcgp: minikube kubectl -- get pods --show-labels
  mkcdp: minikube kubectl -- describe pod
  mkcl: minikube kubectl -- logs
  # Ansible
  a-p: ansible-playbook
  a-i: ansible-inventory
  a-g: ansible-galaxy
  a-l: ansible-lint
  # Others
  clr: clear
  vbm: vboxmanage
  cmq: mysql -h 127.0.0.1 -uroot -pmysql57
  crs: redis-cli -h 127.0.0.1 -p 6379 -a redis
