---
- name: Install role {{ role_name }} dependencies
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl

- name: Add k8s apt key
  become: true
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg 
    keyring: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: Add k8s apt repository
  become: true
  apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes.list

- name: Install kubelet kubeadm kubectl
  become: true
  apt:
    update_cache: true
    pkg:
      - "kubelet={{ k8s_default_version }}"
      - "kubeadm={{ k8s_default_version }}"
      - "kubectl={{ k8s_default_version }}"

- name: Hold kubelet kubeadm kubectl
  become: true
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable CRI plugin
  become: true
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins\s*=\s*\[.*\]$'
    line: 'enabled_plugins = ["cri"]'

- name: Add CRI configuration
  become: true
  blockinfile:
    path: /etc/containerd/config.toml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      [plugins."io.containerd.grpc.v1.cri".containerd]
        endpoint = "unix:///var/run/containerd/containerd.sock"
    insertafter: '^enabled_plugins =.*$'

- name: Restart containerd service
  become: true
  systemd:
    name: containerd
    state: restarted
