---
- name: Check if Plugin zsh-autosuggestions exists
  stat:
    path: "{{ omz.custom_plugins }}/zsh-autosuggestions"
  register: plugin_zsh_autosuggestions

- name: Download Plugin zsh-autosuggestions if not exists
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ omz.custom_plugins }}/zsh-autosuggestions"
    version: master
    update: false
  when: not plugin_zsh_autosuggestions.stat.exists

- name: Include alias varsfile
  include_vars: alias.yml

- name: Add alias to zshrc
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "alias {{ item.key }}='{{ item.value }}' "
  with_dict: "{{ zsh_alias }}"

- name: Customize Lines
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      # Settings java
      export JAVA_HOME="{{ java_home }}"
      # Settings gvm
      [[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
      # Customize ZSH PROMPT
      PROMPT='%F{cyan}[$(whoami) $(hostname)]%f Î» %~/ $(git_prompt_info)%{$reset_color%}'
      # Enable volta pnpm support
      export VOLTA_FEATURE_PNPM=1
      source $HOME/.profile
    marker: "### ANSIBLE MANAGED CUSTOM BLOCK ###"

- name: Customize Lines in .profile
  blockinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
    marker: "### ANSIBLE MANAGED CUSTOM BLOCK IN .profile ###"

- name: Create ~/.zprofile if not exists
  file:
    path: "{{ ansible_env.HOME }}/.zprofile"
    state: touch
    mode: "0664"
