---
# handlers file for role {{ role_name }}

- name: Install dependencies for hashicorp
  become: true
  apt:
    pkg:
      - wget
  listen: Setup hashicorp

- name: Add hashicorp apt key
  become: true
  apt_key:
    url: "{{ hashicorp_repo_url }}/gpg"
    keyring: "{{ hashicorp_keyring }}"
    state: present
  listen: Setup hashicorp

- name: Add hashicorp apt repository
  become: true
  apt_repository:
    repo: "deb [signed-by={{ hashicorp_keyring }}] {{ hashicorp_repo_url }} {{ ansible_distribution_release }} main"
    state: present
    filename: /etc/apt/sources.list.d/hashicorp.list
  listen: Setup hashicorp
