- name: Install kubectl
  import_tasks: kubectl.yml
  when: "'master' in group_names"

- name: Install helm
  import_tasks: helm.yml
  when: "'master' in group_names"

- name: Install kubernetes requirement tools
  import_tasks: tools.yml
  when: "'master' in group_names"
