---
- name: Download volta installer if not exists
  connection: local
  get_url:
    url: https://get.volta.sh
    dest: /tmp/volta-installer
    mode: "0755"
    force: false

- name: Install volta by volta installer
  script: /tmp/volta-installer
  args:
    executable: /bin/bash
    creates: "{{ volta_root }}"

- name: Install node ( Default Version is {{ node_default_version }} ) and pnpm
  shell: |
    volta install node@{{ node_default_version }} 
    volta install pnpm@latest
  args:
    executable: /bin/zsh
