---
- name: Download and install minikube deb file
  become: true
  apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

- name: Download and install cri-dockerd (Kubernetes v1.24+ requires) deb file
  become: true
  apt:
    deb: "{{ cridockerd_pkg_url }}"
