---
- name: Download pyenv-installer
  connection: local
  get_url:
    url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
    dest: "/tmp"
    mode: "0755"
    force: false

- name: Install pyenv by pyenv-installer
  script: /tmp/pyenv-installer
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.pyenv"

- name: Setting pyenv in bash
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ item }}"
  loop:
    - export PYENV_ROOT="$HOME/.pyenv"
    - export PATH="$PYENV_ROOT/bin:$PATH"
    - eval "$(pyenv init --path)"

- name: Update apt cache and install dependencies
  become: true
  apt:
    update_cache: true
    pkg:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev

- name: Create ~/.pyenv/cache if not exists
  file:
    path: "{{ pyenv_cache }}"
    state: directory
    mode: '0755'

- name: Download python3 ( Default Version is {{ python_default_version }} )
  get_url:
    url: "https://npm.taobao.org/mirrors/python/{{ python_default_version }}/Python-{{ python_default_version }}.tar.xz"
    dest: "{{ pyenv_cache }}/Python-{{ python_default_version }}.tar.xz"
    mode: "0755"
    force: false

- name: Install python3
  shell: |
    export PYENV_ROOT="{{ pyenv_root }}"
    export PATH="{{ pyenv_root }}/bin:{{ ansible_env.PATH }}"
    eval "$(pyenv init --path)"
    pyenv install {{ python_default_version }}
    pyenv global {{ python_default_version }}
    pip3 install --upgrade pip
  args:
    executable: /bin/bash
    creates: "{{ pyenv_root }}/shims/python3"
