---
- name: Download pyenv-installer
  get_url:
    url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
    dest: "/tmp"
    mode: '0755'

- name: Install pyenv by pyenv-installer
  command: /bin/sh /tmp/pyenv-installer
  args:
    creates: "{{ home_path }}/.pyenv"
  register: results

- name: Display Debug
  debug:
    var: results.stdout
        # - name: Load pyenv
        #   changed_when: false
        #   shell: |
        #     export PYENV_ROOT="{{ PYENV_ROOT }}"
        #     export PATH="{{ PATH }}"
        #     eval "$(pyenv init --path)"
        #   args:
        #     executable: /bin/bash

        # - name: Setting pyenv in bash
        #   lineinfile:
        #     path: $HOME/.bashrc
        #     line: "{{ item }}"
        #   loop:
        #     - export PYENV_ROOT="{{ PYENV_ROOT }}"
        #     - export PATH="{{ PATH }}"
        #     - eval "$(pyenv init --path)"


    # - name: Install python3 ( Default Version is {{ python_default_version }} ) on worker node
