---
- name: Init SSH Connection
  connection: local
  import_tasks: sshkey.yml
  tags: sshkey

- name: Sync time
  import_tasks: sync_time.yml
  tags: sync_time

- name: Update git
  import_tasks: upgrade_git.yml
  tags: git
