---
- name: Init SSH Connection
  connection: local
  import_tasks: sshkey.yml
  tags: sshkey

- name: Install pyenv and python3 on worker node
  vars:
    pyenv_root: "{{ ansible_env.HOME }}/.pyenv"
    pyenv_cache: "{{ pyenv_root }}/cache"
  environment:
    PYENV_ROOT: "{{ ansible_env.HOME }}/.pyenv"
  import_tasks: install_python.yml
