---
- name: Init SSH Connection
  connection: local
  vars:
    private_key: "{{ node_env.HOME }}/.ssh/id_rsa"
    public_key: "{{ node_env.HOME }}/.ssh/id_rsa.pub"
  import_tasks: sshkey.yml
  tags: sshkey

- name: Sync time
  import_tasks: sync_time.yml
  tags: sync_time

- name: Update git
  import_tasks: git.yml
  tags: git
